basePath: /api/v1/timetable
host: localhost:8080
info:
  contact: {}
  description: This is a sample server Petstore server.
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /teachers:
    get:
      description: Get all teachers IDs
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Get all teachers IDs
      tags:
      - teachers
swagger: "2.0"
