basePath: /api/v1/timetable
host: localhost:8080
info:
  contact: {}
  description: This is a sample server Petstore server.
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /teachers:
    get:
      description: Get all teachers IDs
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
        "404":
          description: Not found
          schema:
            type: string
        "406":
          description: Not acceptable
          schema:
            type: string
        "415":
          description: Unsupported media type
          schema:
            type: string
        "429":
          description: Too many requests
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
        "502":
          description: Bad gateway
          schema:
            type: string
        "503":
          description: Service unavailable
          schema:
            type: string
        "504":
          description: Gateway timeout
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Get all teachers IDs
      tags:
      - teachers
swagger: "2.0"
